### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by kw005** [mschout/perl-number-libphonenumber#1]
Just wanted to install that module.  But where do I find the Makefile.PL ?

**Comment by mschout** [comment]
This module is packaged with Dist::Zilla.  You have two options:

1: check out the build/releases branch. Thats one has Makefile.PL in it and install normally.

2: build on master branch, but you need to install Dist::Zilla as well as the plugin dependencies.  Something like:

   cpanm Dist::Zilla
   dzil authordeps --missing | cpanm
